from __future__ import annotations

"""Daily Loop summary markdown writer.

One file per local date: `{out_dir}/YYYY-MM-DD.md`. Each file is a full
overwrite from a DailyLoopSummary — no append, no merge. Rerunning a date
produces an updated file from scratch.
"""

import logging
from datetime import datetime, timedelta, timezone, tzinfo
from pathlib import Path
from zoneinfo import ZoneInfo

from health_sync.parsers.loop_rollup import DailyLoopSummary

logger = logging.getLogger(__name__)


def _display_tz(summary: DailyLoopSummary, fallback_tz: str) -> tzinfo:
    """Timezone for rendering clock times, matching the header's claim.

    When records carried their own timezoneOffset, the header describes the
    day in that offset — clock times must use it too, not the configured
    person timezone (which is only a fallback for offset-less records).
    """
    if summary.primary_timezone_offset_minutes is not None:
        return timezone(timedelta(minutes=summary.primary_timezone_offset_minutes))
    return ZoneInfo(fallback_tz)


def _format_hypo_event(start_utc, end_utc, duration_min, nadir, level, local_tz: tzinfo) -> str:
    """Format one hypo event line as local-time."""
    start_local = start_utc.astimezone(local_tz)
    end_local = end_utc.astimezone(local_tz)
    return (
        f"- **Level {level}**: {start_local.strftime('%H:%M')}–"
        f"{end_local.strftime('%H:%M')} ({duration_min:.0f} min), "
        f"nadir {nadir:.0f} mg/dL"
    )


def render_daily_summary(summary: DailyLoopSummary, tz: str = "America/Los_Angeles") -> str:
    """Render a DailyLoopSummary as markdown."""
    confidence_note = (
        f"\n_Low-confidence day: CGM coverage {summary.coverage_pct}% < 70%._"
        if summary.low_confidence
        else ""
    )

    if summary.is_travel_day:
        confidence_note += (
            "\n_Travel day: records span multiple timezones. "
            "Binned by local timezone at time of recording, "
            "which may differ from Tidepool's web UI display (viewer timezone)._"
        )
    elif summary.primary_timezone_offset_minutes is not None:
        hrs = summary.primary_timezone_offset_minutes / 60
        confidence_note += (
            f"\n_Records on this day were timestamped at UTC{hrs:+g}h._"
        )

    if summary.hypo_events:
        local_tz = _display_tz(summary, tz)
        hypo_lines = "\n".join(
            _format_hypo_event(
                e.start_utc, e.end_utc, e.duration_minutes, e.nadir_mgdl, e.level, local_tz
            )
            for e in summary.hypo_events
        )
        hypo_section = f"\n## Hypoglycemia events\n\n{hypo_lines}\n"
    else:
        hypo_section = "\n## Hypoglycemia events\n\nNone.\n"

    if summary.primary_timezone_offset_minutes is None:
        tz_label = tz
    else:
        tz_label = (
            f"UTC{summary.primary_timezone_offset_minutes / 60:+g}h "
            "(from record timezoneOffset)"
        )

    return f"""# Loop telemetry — {summary.local_date.isoformat()}

_Generated by mychart-sync from Tidepool data. Local timezone: {tz_label}._{confidence_note}

## Glycemic summary

| Metric | Value |
|---|---|
| Mean glucose | **{summary.mean_glucose_mgdl} mg/dL** |
| GMI (estimated A1c) | **{summary.gmi_pct:.2f}%** |
| CV (variability) | {summary.cv_pct}% |
| CGM coverage | {summary.coverage_pct}% ({summary.cgm_count} readings) |

## Time in range (% of covered time, CGM only)

| Band | mg/dL | % |
|---|---|---|
| TIR (target) | 70–180 | **{summary.tir_70_180_pct}%** |
| TBR level 1 | < 70 | {summary.tbr_lt_70_pct}% |
| TBR level 2 | < 54 | {summary.tbr_lt_54_pct}% |
| TAR level 1 | > 180 | {summary.tar_gt_180_pct}% |
| TAR level 2 | > 250 | {summary.tar_gt_250_pct}% |

## Insulin & carbs

| | |
|---|---|
| Manual bolus | {summary.bolus_units} U |
| Loop-delivered | {summary.basal_units} U |
| **TDD** | **{summary.tdd_units} U** |
| Carbs logged | {summary.total_carbs_g:.0f} g |
{hypo_section}
_Manual bolus = user-issued boluses (subType=normal). Loop-delivered = scheduled + automated basal + Loop's algorithm-issued micro-boluses (subType=automated). TDD matches what Tidepool reports as Total Insulin._
"""


def write_daily_summary(
    summary: DailyLoopSummary,
    out_dir: Path,
    tz: str = "America/Los_Angeles",
) -> Path:
    """Write a daily summary markdown file. Full overwrite from summary."""
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{summary.local_date.isoformat()}.md"
    out_path.write_text(render_daily_summary(summary, tz=tz))
    return out_path
